spring:
  profiles:
    active: dev

---
server:
  port: 8021
spring:
  profiles: dev
  application:
    name: springcloud-config-dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

---
server:
  port: 8022
spring:
  profiles: test
  application:
    name: springcloud-config-test
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
